---
title: Testing for bibliography and citations
author: Package Build
date: '2022-11-17'
slug: testing-for-bibliography-and-citations
categories:
  - bibliography
tags: []
bibliography: ../../bibliography.bib
link-citations: FALSE
biblio-style: "apalike"
---

**ABSTRACT**: In the course of the first millennium of its history (c.600–1600 CE), Islamic society evolved from a simple tribal polity into a multifaceted social, cultural, and political entity that stretched from Spain and North Africa in the West to Central Asia and India in the East. Arabic chronicles and biographical collections preserve a plethora of information on long-term environmental and societal processes that shaped and molded Islamic society over this period. Numerous and extensive, these written texts are the richest “mine” of information and are particularly valuable for the period before the 15th century, for which exceptionally few documents and archives are available. The Emmy-Noether Project (ENP) will undertake an innovative study of “The Evolution of Islamic Societies (c. 600-1600 CE)” through the computational analysis of these historical texts, which—for the first time—will be treated holistically as a unified corpus of historical information (c.300 titles; 100 million words; c.400,000 biographical records).[^fn14]

[^fn14]: [@EderStylometry2016]

The ENP’s team of the PI and two Ph.D. candidates will work on identifying and analyzing long-term historical trends through three closely connected case studies. The first one will study major ethnic, religious, and professional groups—and how they shaped the development of local communities and fused them into what we call the Islamic world. The second case study will study dynastic cycles through the patterns of the rise and fall of regional powers, their conflicts with rivals, and interactions with local communities. The third case study will trace patterns of environmental factors—plagues, famines, droughts, pest infestations, earthquakes, and climate change—and their effect on the life of local communities. Complementing and informing each other, these case studies will be the foundation for the PI’s robust synthesis of the evolution of the Islamic world over the period under study.

In order to overcome the complexity and sheer volume of medieval Arabic historical sources, as well as to analyze them in an effective and reproducible manner, the ENP will employ a series of advanced computational methods of text analysis and data modeling that have been developed under the umbrella of digital humanities in recent years. The proposed methodological approach will be the key to discovering, evaluating, and modeling all relevant textual evidence at an unprecedented scale. Finally, the ENP will produce six interconnected research publications: two PhD theses; a methodological handbook and a collection of articles—both co-written with international partners; a Longue Durée Atlas of Islam; and the PI’s monograph that will conclusively present the ENP’s results and its novel computational approach. Last but not least, the ENP will produce an open and expandable online research ecosystem, MasterChronicle, which will allow scholars in the field to engage in various modes of close and distant reading of the Arabic historical corpus.

Qul aʿūḏu ...

**Bibliography**